package MODELO;
// Generated 21 ene. 2022 20:35:29 by Hibernate Tools 5.4.32.Final

/**
 * Ciudadano generated by hbm2java
 */
public class Ciudadano implements java.io.Serializable {

	private int idCiudadano;
	private String partido;
	private String comunidad;
	private int edad;

	public Ciudadano() {
	}

	public Ciudadano(int idCiudadano, String partido, String comunidad, int edad) {
		this.idCiudadano = idCiudadano;
		this.partido = partido;
		this.comunidad = comunidad;
		this.edad = edad;
	}

	public int getIdCiudadano() {
		return this.idCiudadano;
	}

	public void setIdCiudadano(int idCiudadano) {
		this.idCiudadano = idCiudadano;
	}

	public String getPartido() {
		return this.partido;
	}

	public void setPartido(String partido) {
		this.partido = partido;
	}

	public String getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(String comunidad) {
		this.comunidad = comunidad;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

}
